services:
  reimagina_urbano_db:
    image: postgres
    container_name: reimagina_urbano_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  reimagina_urbano_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reimagina_urbano_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    depends_on:
      reimagina_urbano_db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    command: ["poetry", "run", "gunicorn", "src.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

  nginx:
    image: nginx:latest
    container_name: reimagina_urbano_nginx
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available  # Mount sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled      # Mount sites-enabled
      - ./certs:/etc/nginx/certs                  # SSL certificates
volumes:
  pgdata: