-- Create the database
CREATE DATABASE reimaginaurbanodb;

-- Connect to the database
\c reimaginaurbanodb;

-- Drop the table if it already exists
DROP TABLE IF EXISTS lots;

-- Create the 'lots' table
CREATE TABLE lots (
    block_area FLOAT,
    prom_ocup FLOAT,
    pro_ocup_c FLOAT,
    graproes FLOAT,
    puntuaje_hogar_digno FLOAT,
    pob_por_cuarto FLOAT,
    area FLOAT,
    num_workers INTEGER,
    lot_area FLOAT,
    unused_area FLOAT,
    unused_ratio FLOAT,
    green_area FLOAT,
    green_ratio FLOAT,
    amenity_area FLOAT,
    amenity_ratio FLOAT,
    parking_area FLOAT,
    parking_ratio FLOAT,
    building_area FLOAT,
    building_ratio FLOAT,
    distance FLOAT,
    minutes FLOAT,
    gravity_score FLOAT,
    accessibility_score FLOAT,
    wasteful_area FLOAT,
    wasteful_ratio FLOAT,
    occupancy INTEGER,
    underutilized_area FLOAT,
    underutilized_ratio FLOAT,
    occupancy_density FLOAT,
    home_density FLOAT,
    combined_score FLOAT,
    latitud FLOAT,
    longitud FLOAT,
    zoning VARCHAR(255),
    max_cos FLOAT,
    max_cus FLOAT,
    min_cav FLOAT,
    building_volume FLOAT,
    building_volume_block FLOAT,
    units_per_built_area FLOAT,
    population INTEGER,
    optimal_cav FLOAT,
    diff_cav FLOAT,
    id VARCHAR(255) PRIMARY KEY,
    cvegeo VARCHAR(255),
    pobtot INTEGER,
    pobfem INTEGER,
    pobmas INTEGER,
    p_0a2 INTEGER,
    p_0a2_f INTEGER,
    p_0a2_m INTEGER,
    p_3a5 INTEGER,
    p_3a5_f INTEGER,
    p_3a5_m INTEGER,
    p_6a11 INTEGER,
    p_6a11_f INTEGER,
    p_6a11_m INTEGER,
    p_12a14 INTEGER,
    p_12a14_f INTEGER,
    p_12a14_m INTEGER,
    p_15a17 INTEGER,
    p_15a17_f INTEGER,
    p_15a17_m INTEGER,
    p_18a24 INTEGER,
    p_18a24_f INTEGER,
    p_18a24_m INTEGER,
    p_60ymas INTEGER,
    p_60ymas_f INTEGER,
    p_60ymas_m INTEGER,
    pea INTEGER,
    pe_inac INTEGER,
    pocupada INTEGER,
    pdesocup INTEGER,
    vivtot INTEGER,
    tvivhab INTEGER,
    tvivpar INTEGER,
    vivpar_hab INTEGER,
    vivpar_des INTEGER,
    ocupvivpar INTEGER,
    tvivparhab INTEGER,
    vph_1cuart INTEGER,
    vph_2cuart INTEGER,
    vph_3ymasc INTEGER,
    vph_pisodt INTEGER,
    vph_tinaco INTEGER,
    vph_excsa INTEGER,
    vph_drenaj INTEGER,
    vph_c_serv INTEGER,
    vph_refri INTEGER,
    vph_lavad INTEGER,
    vph_autom INTEGER,
    vph_tv INTEGER,
    vph_pc INTEGER,
    vph_telef INTEGER,
    vph_cel INTEGER,
    vph_inter INTEGER,
    vph_stvp INTEGER,
    vph_spmvpi INTEGER,
    vph_cvj INTEGER,
    pafil_ipriv INTEGER,
    pcatolica INTEGER,
    pro_crieva INTEGER,
    potras_rel INTEGER,
    psin_relig INTEGER,
    p_25a59_f INTEGER,
    p_25a59_m INTEGER,
    p_25a59 INTEGER,
    total_cuartos INTEGER,
    num_establishments INTEGER,
    num_properties INTEGER,
    num_floors FLOAT,
    max_height FLOAT,
    diff_height FLOAT,
    max_home_units INTEGER,
    units_estimate INTEGER,
    potential_new_units INTEGER
);
