-- Create the database
CREATE DATABASE reimaginaurbano;

-- Connect to the database
\c reimaginaurbano;

-- Drop the tables if they already exist
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS lots;
DROP TABLE IF EXISTS accessibility_trips;

-- Create the 'blocks' table
CREATE TABLE blocks (
    cvegeo VARCHAR(255) PRIMARY KEY,
    block_area FLOAT,
    pobtot INTEGER,
    pobfem INTEGER,
    pobmas INTEGER,
    p_0a2 INTEGER,
    p_0a2_f INTEGER,
    p_0a2_m INTEGER,
    p_3a5 INTEGER,
    p_3a5_f INTEGER,
    p_3a5_m INTEGER,
    p_6a11 INTEGER,
    p_6a11_f INTEGER,
    p_6a11_m INTEGER,
    p_12a14 INTEGER,
    p_12a14_f INTEGER,
    p_12a14_m INTEGER,
    p_15a17 INTEGER,
    p_15a17_f INTEGER,
    p_15a17_m INTEGER,
    p_18a24 INTEGER,
    p_18a24_f INTEGER,
    p_18a24_m INTEGER,
    p_60ymas INTEGER,
    p_60ymas_f INTEGER,
    p_60ymas_m INTEGER,
    pea INTEGER,
    pe_inac INTEGER,
    pocupada INTEGER,
    pdesocup INTEGER,
    vivtot INTEGER,
    tvivhab INTEGER,
    tvivpar INTEGER,
    vivpar_hab INTEGER,
    vivpar_des INTEGER,
    ocupvivpar INTEGER,
    prom_ocup FLOAT,
    pro_ocup_c FLOAT,
    tvivparhab INTEGER,
    vivparh_cv INTEGER,
    vph_1cuart INTEGER,
    vph_2cuart INTEGER,
    vph_3ymasc INTEGER,
    vph_pisodt INTEGER,
    vph_tinaco INTEGER,
    vph_excsa INTEGER,
    vph_drenaj INTEGER,
    vph_c_serv INTEGER,
    vph_refri INTEGER,
    vph_lavad INTEGER,
    vph_autom INTEGER,
    vph_tv INTEGER,
    vph_pc INTEGER,
    vph_telef INTEGER,
    vph_cel INTEGER,
    vph_inter INTEGER,
    vph_stvp INTEGER,
    vph_spmvpi INTEGER,
    vph_cvj INTEGER,
    pafil_ipriv INTEGER,
    graproes FLOAT,
    pcatolica INTEGER,
    pro_crieva INTEGER,
    potras_rel INTEGER,
    psin_relig INTEGER,
    p_25a59_f INTEGER,
    p_25a59_m INTEGER,
    p_25a59 INTEGER,
    puntuaje_hogar_digno FLOAT,
    total_cuartos INTEGER,
    pob_por_cuarto FLOAT,
    accessibility_score FLOAT,
    minutes FLOAT,
    node_ids BIGINT,
    latitud FLOAT,
    longitud FLOAT
);

-- Create the 'lots' table
CREATE TABLE lots (
    lot_id VARCHAR(255) PRIMARY KEY,
    cvegeo VARCHAR(255),
    block_area FLOAT,
    lot_area FLOAT,
    unused_area FLOAT,
    unused_ratio FLOAT,
    green_area FLOAT,
    green_ratio FLOAT,
    amenity_area FLOAT,
    amenity_ratio FLOAT,
    parking_area FLOAT,
    parking_ratio FLOAT,
    building_area FLOAT,
    building_ratio FLOAT,
    wasteful_area FLOAT,
    wasteful_ratio FLOAT,
    underutilized_area FLOAT,
    underutilized_ratio FLOAT,
    occupancy_density FLOAT,
    home_density FLOAT,
    latitud FLOAT,
    longitud FLOAT,
    zoning VARCHAR(255),
    max_cos FLOAT,
    max_cus FLOAT,
    min_cav FLOAT,
    max_num_levels INTEGER,
    max_home_units INTEGER,
    cos FLOAT,
    cus FLOAT,
    per_cos FLOAT,
    per_cus FLOAT,
    block_cus FLOAT,
    num_levels INTEGER,
    home_units INTEGER,
    potential_home_units INTEGER,
    population INTEGER,
    num_workers INTEGER,
    num_establishments INTEGER,
    num_properties INTEGER,
    mean_slope FLOAT
);

CREATE TABLE accessibility_trips (
    origin_id BIGINT,
    destination_id BIGINT,
    num_amenity INTEGER,
    amenity VARCHAR(255),
    distance FLOAT,
    minutes FLOAT,
    gravity FLOAT,
    population FLOAT,
    attraction FLOAT,
    pob_reach FLOAT,
    accessibility_score FLOAT,
    node_ids VARCHAR(255)
);

CREATE INDEX id ON accessibility_trips (origin_id, destination_id, num_amenity);
