name: Build and Deploy FastAPI to Azure Web App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Build and Push Docker Image'
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reimaginaurbano:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reimaginaurbano:${{ github.sha }}
